/** Auto-generated iNaturalist default photos — run `npm run fetch-species-images` to refresh. */
export const SPECIES_IMAGE_URLS: Record<string, string> = {
  "turdus-migratorius":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/34859026/medium.jpg",
  "cardinalis-cardinalis":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/189434971/medium.jpg",
  "buteo-jamaicensis":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/236676280/medium.jpg",
  "bombycilla-cedrorum":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/450146514/medium.jpeg",
  "cyanocitta-cristata":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/530721418/medium.jpg",
  "passerina-cyanea":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/168808461/medium.jpeg",
  "icterus-galbula":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/155708903/medium.jpg",
  "passerina-ciris":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/293862280/medium.jpeg",
  "spinus-tristis":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/384965723/medium.jpg",
  "bubo-scandiacus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/150549757/medium.jpg",
  "poecile-atricapillus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/178279576/medium.jpg",
  "sitta-carolinensis":
    "https://static.inaturalist.org/photos/25544020/medium.jpeg",
  "dryobates-pubescens":
    "https://static.inaturalist.org/photos/25544008/medium.jpeg",
  "dryobates-villosus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/1275/medium.jpg",
  "melanerpes-carolinus":
    "https://static.inaturalist.org/photos/383227697/medium.jpeg",
  "dryocopus-pileatus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/168915535/medium.jpg",
  "zenaida-macroura":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/14015355/medium.jpg",
  "haemorhous-mexicanus":
    "https://static.inaturalist.org/photos/178968933/medium.jpg",
  "passer-domesticus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/4608133/medium.jpg",
  "sturnus-vulgaris":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/32152001/medium.jpg",
  "quiscalus-quiscula":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/265296529/medium.jpg",
  "molothrus-ater":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/656878277/medium.jpg",
  "agelaius-phoeniceus":
    "https://static.inaturalist.org/photos/368048127/medium.jpg",
  "corvus-brachyrhynchos":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/4661023/medium.jpg",
  "corvus-corax":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/54389687/medium.jpg",
  "cathartes-aura":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/52277010/medium.jpg",
  "accipiter-cooperii":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/170370008/medium.jpg",
  "accipiter-striatus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/112860673/medium.jpeg",
  "falco-sparverius":
    "https://static.inaturalist.org/photos/174574440/medium.jpg",
  "falco-peregrinus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/212499566/medium.jpg",
  "ardea-herodias":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/65060931/medium.jpg",
  "branta-canadensis":
    "https://static.inaturalist.org/photos/181719420/medium.jpg",
  "anas-platyrhynchos":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/95268822/medium.jpg",
  "aix-sponsa":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/171626985/medium.jpg",
  "haliaeetus-leucocephalus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/341016703/medium.jpeg",
  "pandion-haliaetus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/6903515/medium.jpg",
  "strix-varia":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/359094470/medium.jpg",
  "bubo-virginianus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/14549085/medium.jpg",
  "archilochus-colubris":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/221352761/medium.jpg",
  "sialia-sialis":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/477069179/medium.jpg",
  "melospiza-melodia":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/104749271/medium.jpg",
  "zonotrichia-albicollis":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/23268661/medium.jpg",
  "junco-hyemalis":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/111714701/medium.jpeg",
  "mimus-polyglottos":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/142697277/medium.jpg",
  "dumetella-carolinensis":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/196664043/medium.jpg",
  "hirundo-rustica":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/122469139/medium.jpg",
  "tachycineta-bicolor":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/196885341/medium.jpeg",
  "chaetura-pelagica":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/383206018/medium.jpeg",
  "charadrius-vociferus":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/15053771/medium.jpg",
  "gavia-immer":
    "https://inaturalist-open-data.s3.amazonaws.com/photos/2960972/medium.jpg",
};
