import type { CatalogSpecies } from "@/lib/speciesCatalog";
import { getCatalogSpeciesById } from "@/lib/speciesCatalog";

export interface SpeciesProfile {
  family: string;
  size: string;
  habitat: string;
  range: string;
  diet: string;
  summary: string;
  field_marks: string[];
  curated: boolean;
}

function p(
  family: string,
  size: string,
  habitat: string,
  range: string,
  diet: string,
  summary: string,
  field_marks: string[],
): SpeciesProfile {
  return { family, size, habitat, range, diet, summary, field_marks, curated: true };
}

function fallbackProfile(species: CatalogSpecies): SpeciesProfile {
  return {
    family: species.family,
    size: "",
    habitat: "",
    range: "",
    diet: "",
    summary: `${species.species} is one of the bird species Burd can identify from photos. Ask below to learn about its habits, range, and field marks.`,
    field_marks: [],
    curated: false,
  };
}

/** Encyclopedia content keyed by catalog species id. Ready to swap for IOC/eBird imports. */
export const SPECIES_PROFILES: Record<string, SpeciesProfile> = {
  "turdus-migratorius": p(
    "Turdidae",
    "9–11 in",
    "Lawns, parks, woodland edges, and suburban yards",
    "Breeds across North America; winters south to central Mexico",
    "Earthworms, insects, and fruit",
    "A familiar harbinger of spring, the American Robin hunts on open ground and nests in trees and shrubs.",
    ["Orange-red breast and dark head", "Yellow bill and white eye arcs", "White undertail coverts visible in flight"],
  ),
  "cardinalis-cardinalis": p(
    "Cardinalidae",
    "8–9 in",
    "Dense shrubs, woodland edges, and backyards with cover",
    "Eastern and central U.S.; southwest U.S. and Mexico",
    "Seeds, fruit, and insects",
    "One of the most recognizable backyard birds, males sing loudly from exposed perches year-round.",
    ["Bright red male with crest and black face mask", "Brown female with red tinges and crest", "Thick orange-red bill"],
  ),
  "buteo-jamaicensis": p(
    "Accipitridae",
    "18–26 in",
    "Open country, fields, highways, and woodland edges",
    "Throughout North America and much of the Americas",
    "Small mammals, birds, and reptiles",
    "The most common large hawk in North America, often seen soaring on broad wings or perched on poles.",
    ["Reddish upper tail from above or below", "Pale belly with dark belly band on many adults", "Broad, rounded wings in flight"],
  ),
  "bombycilla-cedrorum": p(
    "Bombycillidae",
    "6–7 in",
    "Open woodlands, orchards, and areas with fruiting trees",
    "Breeds in Canada and northern U.S.; winters across southern U.S. and Mexico",
    "Fruit and insects",
    "Sleek, social birds that travel in flocks to feast on berries, often passing fruit between individuals.",
    ["Sleek brown body with pale yellow belly", "Black mask and waxy red tips on wing feathers", "Crest and short bill"],
  ),
  "cyanocitta-cristata": p(
    "Corvidae",
    "9–12 in",
    "Deciduous and mixed forests, parks, and suburbs",
    "Eastern and central North America",
    "Acorns, nuts, insects, and eggs of other birds",
    "Bold and vocal, Blue Jays are intelligent corvids that cache food and mimic hawk calls.",
    ["Bright blue above with white and black pattern", "Blue crest", "Noisy, harsh calls"],
  ),
  "passerina-cyanea": p(
    "Cardinalidae",
    "5–6 in",
    "Brushy edges, woodland openings, and hedgerows",
    "Eastern U.S.; winters in Central America and Caribbean",
    "Insects, seeds, and berries",
    "Breeding males are an unmistakable deep blue; females are warm brown with subtle blue tones.",
    ["Male entirely deep blue with darker wings and tail", "Silver-gray bill", "Sweet warbling song from treetops"],
  ),
  "icterus-galbula": p(
    "Icteridae",
    "7–8 in",
    "Open woodlands, riparian areas, and parks with tall trees",
    "Eastern and central North America; winters in Central America and northern South America",
    "Insects, fruit, and nectar",
    "A striking orange-and-black oriole that weaves hanging nests and visits feeders for oranges and jelly.",
    ["Bright orange underparts with black head and back", "White wing bar", "Chattering, flute-like song"],
  ),
  "passerina-ciris": p(
    "Cardinalidae",
    "5–5.5 in",
    "Coastal scrub, woodland edges, and brushy fields",
    "Southern U.S. and northern Mexico; winters in Central America",
    "Seeds and insects",
    "Often called the most colorful North American bird, males combine red, blue, and green in one plumage.",
    ["Male: red underparts, blue head, green back", "Greenish female", "Thick, conical bill"],
  ),
  "spinus-tristis": p(
    "Fringillidae",
    "4–5 in",
    "Weedy fields, gardens, and open woodlands",
    "Most of North America; partial migrant",
    "Seeds, especially thistle and sunflower",
    "A small finch that molts into brilliant yellow breeding plumage and bounces through flight calling sweetly.",
    ["Breeding male bright yellow with black cap and wings", "White wing bars and notched tail", "Undulating flight pattern"],
  ),
  "bubo-scandiacus": p(
    "Strigidae",
    "20–28 in",
    "Tundra, open fields, airports, and coastal dunes in irruption years",
    "Arctic breeder; irrupts south into U.S. and southern Canada in winter",
    "Lemmings, voles, and other small mammals",
    "A powerful Arctic owl that occasionally appears far south in winter during food-driven irruptions.",
    ["Mostly white plumage with variable dark barring", "Yellow eyes and no ear tufts", "Diurnal hunter in open habitats"],
  ),
  "poecile-atricapillus": p(
    "Paridae",
    "4.5–5.5 in",
    "Deciduous and mixed forests, parks, and feeders",
    "Northern U.S., Canada, and Alaska",
    "Insects, seeds, and suet",
    "Curious and acrobatic, chickadees are bold at feeders and hide seeds to retrieve later.",
    ["Black cap and bib with white cheeks", "Gray back and buffy sides", "Fee-bee song and chick-a-dee calls"],
  ),
  "sitta-carolinensis": p(
    "Sittidae",
    "5–6 in",
    "Mature deciduous and mixed forests with large trees",
    "Much of the eastern and central U.S.",
    "Insects and seeds cached in bark",
    "Climbs head-first down tree trunks, probing bark crevices for insects and stashing seeds.",
    ["Blue-gray above, white face and underparts", "Black cap (male) or gray cap (female)", "Long, straight bill"],
  ),
  "dryobates-pubescens": p(
    "Picidae",
    "5.5–6.5 in",
    "Woodlands, parks, and backyards with trees",
    "Most of North America except far southwest",
    "Insects and plant sap",
    "North America's smallest woodpecker, drumming on dead limbs and visiting suet feeders.",
    ["Black-and-white barred back", "White outer tail feathers", "Male has small red nape patch; bill shorter than head"],
  ),
  "dryobates-villosus": p(
    "Picidae",
    "7–10 in",
    "Forests, woodlots, and wooded suburbs",
    "Most of North America except far southwest",
    "Insects and fruit",
    "Looks like a larger Downy Woodpecker; bill length relative to head is the best field mark.",
    ["Black-and-white pattern like Downy", "Bill longer than head width", "No red on crown in either sex (male has red nape)"],
  ),
  "melanerpes-carolinus": p(
    "Picidae",
    "9–10 in",
    "Deciduous forests, woodlands, and suburban areas",
    "Eastern U.S. and southern Ontario",
    "Insects, nuts, fruit, and seeds",
    "Named for a faint reddish wash on the belly, not the vivid red cap shared by both sexes.",
    ["Pale gray face and tan belly", "Black-and-white barred back", "Red cap on male and female"],
  ),
  "dryocopus-pileatus": p(
    "Picidae",
    "16–19 in",
    "Mature forests with large dead trees",
    "Forested regions across North America",
    "Carpenter ants and wood-boring insects",
    "North America's largest common woodpecker, leaving rectangular excavations in dead wood.",
    ["Crested black body with white neck stripes", "Male has red malar stripe", "Powerful, loud drumming"],
  ),
  "zenaida-macroura": p(
    "Columbidae",
    "9–13 in",
    "Open country, suburbs, parks, and woodland edges",
    "Most of North America south to Panama",
    "Seeds and grains",
    "Slender, fast-flying doves common in yards and fields, with a soft, mournful song.",
    ["Slim body with long pointed tail", "Pale pinkish breast and blue orbital ring", "Wings whistle on takeoff"],
  ),
  "haemorhous-mexicanus": p(
    "Fringillidae",
    "5–6 in",
    "Suburbs, deserts, grasslands, and open woodland",
    "Most of North America; native west, expanded east",
    "Seeds, buds, and fruit",
    "A adaptable finch with rosy-red on males; males sing from high perches in spring.",
    ["Male rosy-red head, breast, and rump", "Brown-streaked female", "Conical bill for seed eating"],
  ),
  "passer-domesticus": p(
    "Passeridae",
    "5–6 in",
    "Urban and suburban areas near human habitation",
    "Introduced; widespread in North America",
    "Seeds and scraps",
    "A familiar introduced sparrow of cities and farms, often nesting in building crevices.",
    ["Chunky brown bird with gray crown (male)", "Black bib on male", "Noisy chirping around feeders and eaves"],
  ),
  "sturnus-vulgaris": p(
    "Sturnidae",
    "7–9 in",
    "Open country, suburbs, and agricultural areas",
    "Introduced; most of North America",
    "Insects, fruit, and seeds",
    "Highly social starlings form large flocks and mimic other birds; iridescent in good light.",
    ["Dark plumage with white speckles in winter", "Short tail and long, pointed wings", "Yellow bill in breeding season"],
  ),
  "quiscalus-quiscula": p(
    "Icteridae",
    "11–13 in",
    "Marshes, lawns, parks, and agricultural fields",
    "Eastern North America",
    "Insects, seeds, and grain",
    "Large, long-tailed blackbird with iridescent plumage and a loud, squeaky song.",
    ["Iridescent purple-blue head and bronze body", "Long tail and heavy bill", "Walks on lawns with tail held high"],
  ),
  "molothrus-ater": p(
    "Icteridae",
    "7–8 in",
    "Open country, pastures, and edges near livestock",
    "Most of North America",
    "Seeds and insects",
    "A brood parasite that lays eggs in other birds' nests, leaving host species to raise its young.",
    ["Stocky brown bird with thick bill", "Short tail and hunched posture", "Follows cattle and other grazing animals"],
  ),
  "agelaius-phoeniceus": p(
    "Icteridae",
    "7–9 in",
    "Fresh and salt marshes, wet meadows, and cattail wetlands",
    "Most of North America",
    "Insects, seeds, and grain",
    "Males defend marsh territories with a conk-la-ree song from cattails and fence posts.",
    ["Male black with red-and-yellow shoulder patch", "Streaked brown female", "Favors cattails and wet fields"],
  ),
  "corvus-brachyrhynchos": p(
    "Corvidae",
    "17–21 in",
    "Almost any habitat including cities, forests, and fields",
    "Most of North America",
    "Omnivorous — carrion, insects, grain, and eggs",
    "Highly intelligent and adaptable, crows gather in family groups and recognize individual humans.",
    ["All black with fan-shaped tail", "Stout bill", "Hoarse cawing calls"],
  ),
  "corvus-corax": p(
    "Corvidae",
    "22–27 in",
    "Wilder areas: mountains, deserts, coasts, and boreal forest",
    "Western and northern North America",
    "Carrion, small animals, and human food waste",
    "Larger than American Crow with a deeper, croaking voice and wedge-shaped tail in flight.",
    ["Massive all-black corvid", "Shaggy throat feathers", "Wedge-shaped tail and deep kronk calls"],
  ),
  "cathartes-aura": p(
    "Cathartidae",
    "25–32 in",
    "Open country, roadsides, and forest edges",
    "Most of the Americas",
    "Carrion",
    "Relies on keen smell to find carrion, often soaring with wings held in a shallow V.",
    ["Dark brown body with bare red head", "Silvery flight feathers from below", "Wobbly, teetering flight on dihedral wings"],
  ),
  "accipiter-cooperii": p(
    "Accipitridae",
    "14–20 in",
    "Woodlands, suburbs, and parks with trees",
    "North America",
    "Mostly birds and small mammals",
    "A woodland hawk built for quick pursuit through trees; sometimes hunts at backyard feeders.",
    ["Long tail with thick dark bands", "Rounded wings in flight", "Adult gray above with reddish barring below"],
  ),
  "accipiter-striatus": p(
    "Accipitridae",
    "9–13 in",
    "Forests and wooded suburbs",
    "North America",
    "Small birds",
    "North America's smallest accipiter, darting through cover to ambush songbirds.",
    ["Small, compact accipiter", "Square tail with thin bands", "Often flies with rapid wingbeats then glides"],
  ),
  "falco-sparverius": p(
    "Falconidae",
    "8–12 in",
    "Open country, grasslands, and urban edges",
    "Most of North America",
    "Insects, small mammals, and birds",
    "North America's smallest falcon, often seen hovering over fields hunting grasshoppers.",
    ["Rusty back and tail on male", "Mustache mark and spotted underparts", "Hovers while hunting"],
  ),
  "falco-peregrinus": p(
    "Falconidae",
    "15–20 in",
    "Cliffs, coasts, cities, and open country near water",
    "Cosmopolitan; breeds across North America",
    "Birds caught in flight",
    "The fastest animal on Earth in a stoop, recovered from DDT-era declines and now nests on skyscrapers.",
    ["Dark hood and malar stripe", "Blue-gray back and barred underparts", "Pointed wings and powerful flight"],
  ),
  "ardea-herodias": p(
    "Ardeidae",
    "38–54 in",
    "Marshes, ponds, rivers, and coastlines",
    "Most of North America and Central America",
    "Fish, amphibians, and small mammals",
    "A patient wader that stalks shallow water and strikes with a dagger-like bill.",
    ["Blue-gray body with white head and neck", "Black plumes on head in breeding season", "Slow flight with neck folded in S-shape"],
  ),
  "branta-canadensis": p(
    "Anatidae",
    "30–43 in",
    "Lakes, ponds, parks, and grassy fields",
    "North America; introduced elsewhere",
    "Grasses, sedges, and grains",
    "Large, honking goose in V-shaped flocks; many populations now resident in suburbs year-round.",
    ["Black head and neck with white chinstrap", "Brown body", "Loud honking in flight"],
  ),
  "anas-platyrhynchos": p(
    "Anatidae",
    "20–26 in",
    "Freshwater wetlands, ponds, and urban parks",
    "Northern Hemisphere; widespread introduced populations",
    "Plants, seeds, and aquatic invertebrates",
    "The ancestor of most domestic ducks, with males showing an iridescent green head in breeding plumage.",
    ["Male: green head, yellow bill, chestnut breast", "Female mottled brown with orange-and-brown bill", "Blue speculum on wing"],
  ),
  "aix-sponsa": p(
    "Anatidae",
    "18–21 in",
    "Wooded swamps, beaver ponds, and tree-lined streams",
    "North America",
    "Acorns, seeds, and aquatic plants",
    "One of the most colorful North American ducks, nesting in tree cavities near water.",
    ["Male ornate with iridescent green head and white stripes", "Female gray with white eye ring", "Perches and nests in trees"],
  ),
  "haliaeetus-leucocephalus": p(
    "Accipitridae",
    "28–40 in",
    "Lakes, rivers, coasts, and fish-rich wetlands",
    "North America",
    "Mostly fish and carrion",
    "A national symbol of the U.S., now recovering and nesting near large bodies of water.",
    ["White head and tail on dark brown body", "Massive yellow bill", "Soars on flat wings with obvious white head and tail"],
  ),
  "pandion-haliaetus": p(
    "Pandionidae",
    "21–24 in",
    "Near fish-rich water: lakes, rivers, estuaries, and coasts",
    "Worldwide; breeds across North America",
    "Fish",
    "A fish-eating specialist that hovers and plunges feet-first, often rebuilding large stick nests on platforms.",
    ["White underparts with dark wrist patch", "Dark brown above with white head", "Reversible outer toe for gripping fish"],
  ),
  "strix-varia": p(
    "Strigidae",
    "16–25 in",
    "Mature deciduous and mixed forests near water",
    "Eastern North America and Pacific Northwest",
    "Small mammals, birds, and amphibians",
    "Known for its who-cooks-for-you call, this owl hunts from perches in wooded swamps and riparian areas.",
    ["Brown-gray barring on chest and vertical streaks below", "Round head without ear tufts", "Dark eyes"],
  ),
  "bubo-virginianus": p(
    "Strigidae",
    "18–25 in",
    "Varied — forests, deserts, suburbs, and parks",
    "Most of North and South America",
    "Mammals, birds, and reptiles",
    "A powerful, adaptable owl with prominent ear tufts and a deep hooting song.",
    ["Large ear tufts and yellow eyes", "Mottled gray-brown plumage", "White throat that inflates when hooting"],
  ),
  "archilochus-colubris": p(
    "Trochilidae",
    "3–3.5 in",
    "Gardens, meadows, and woodland edges with flowers",
    "Eastern North America; winters in Central America",
    "Nectar and small insects",
    "The only breeding hummingbird in most of eastern North America, visiting feeders and tubular flowers.",
    ["Male: iridescent red throat, green back", "Female green above, whitish below", "Wings make a humming sound in flight"],
  ),
  "sialia-sialis": p(
    "Turdidae",
    "6.5–8 in",
    "Open country with scattered trees, meadows, and orchards",
    "Eastern North America and Mexico",
    "Insects and berries",
    "A gentle thrush of fields and fence posts, often using nest boxes in open habitat.",
    ["Male bright blue above, rusty breast", "Female duller with blue wings and tail", "Perches on wires and posts"],
  ),
  "melospiza-melodia": p(
    "Passerellidae",
    "5–7 in",
    "Marshes, thickets, gardens, and brushy edges",
    "Most of North America",
    "Seeds and insects",
    "One of the most variable sparrows in plumage, recognized by streaked breast with a central spot.",
    ["Streaked brown back and breast spot", "Gray eyebrow and malar stripe", "Melodic, varied song"],
  ),
  "zonotrichia-albicollis": p(
    "Passerellidae",
    "6–7 in",
    "Brushy woodland, forest edges, and suburban thickets",
    "Breeds in Canada and northern U.S.; winters in eastern and southern U.S.",
    "Seeds and insects",
    "A crisp-looking sparrow with bold head stripes and a whistled oh-sweet-canada-canada song.",
    ["Black-and-white striped head", "Yellow lores in front of eye", "Gray breast and rufous wings"],
  ),
  "junco-hyemalis": p(
    "Passerellidae",
    "5–6 in",
    "Forests, parks, and feeders in winter",
    "Breeds in Canada and western mountains; winters across U.S.",
    "Seeds and insects",
    "Called snowbirds in the east, dark-eyed juncos flock under feeders with white outer tail flashes.",
    ["Slate-gray or brown forms depending on region", "Pink bill", "White outer tail feathers in flight"],
  ),
  "mimus-polyglottos": p(
    "Mimidae",
    "8–11 in",
    "Suburbs, parks, open country with shrubs and fences",
    "Southern Canada to Mexico",
    "Insects, fruit, and berries",
    "An excellent mimic that repeats phrases of other birds and mechanical sounds from exposed perches.",
    ["Gray above, whitish below", "White wing patches and outer tail feathers", "Long tail often held partly open"],
  ),
  "dumetella-carolinensis": p(
    "Mimidae",
    "8–9 in",
    "Dense shrubs, woodland edges, and suburban hedges",
    "Eastern and central North America",
    "Insects and fruit",
    "A skulking gray bird with a cat-like mew call, often hidden in tangles but vocal in summer.",
    ["Slate gray overall with black cap", "Rusty undertail coverts", "Black cap and tail"],
  ),
  "hirundo-rustica": p(
    "Hirundinidae",
    "6–7 in",
    "Open country near barns, bridges, and water",
    "North America; winters in Central and South America",
    "Flying insects",
    "Classic barn swallow of farms, catching insects over fields with deeply forked tail.",
    ["Steel-blue upperparts", "Rusty forehead and underparts", "Long forked tail with white spots"],
  ),
  "tachycineta-bicolor": p(
    "Hirundinidae",
    "5–6 in",
    "Open country near water with nest cavities",
    "North America; winters in Central America and Caribbean",
    "Flying insects",
    "Iridescent green above and clean white below, often nesting in boxes near ponds and marshes.",
    ["Glossy greenish-blue back and white underparts", "Short notched tail", "Chattering over water"],
  ),
  "chaetura-pelagica": p(
    "Apodidae",
    "5–5.5 in",
    "Urban areas, chimneys, and open sky over towns",
    "Eastern North America; winters in South America",
    "Flying insects",
    "A cigar-shaped swift that spends almost its entire life on the wing, roosting communally in chimneys.",
    ["Dark sooty brown body", "Long narrow wings", "Twittering calls high overhead"],
  ),
  "charadrius-vociferus": p(
    "Charadriidae",
    "9–11 in",
    "Open ground — lawns, gravel, fields, and shorelines",
    "North and Central America",
    "Insects and worms",
    "Named for its loud kill-deer call, this plover performs a broken-wing distraction display near nests.",
    ["Brown upperparts with two black breast bands", "Red eye ring", "Long legs and runs quickly on open ground"],
  ),
  "gavia-immer": p(
    "Gaviidae",
    "28–36 in",
    "Breeds on northern lakes; winters on coastal and inland waters",
    "North America; breeds in Canada and northern U.S.",
    "Fish and aquatic invertebrates",
    "An icon of northern lakes with yodeling calls and striking black-and-white breeding plumage.",
    ["Breeding: black head, white checkerboard back", "Red eye and dagger bill", "Low in water with feet set far back"],
  ),
};

export function getCuratedSpeciesProfile(id: string): SpeciesProfile | null {
  return SPECIES_PROFILES[id] ?? null;
}

export function getSpeciesProfile(
  id: string,
  species?: CatalogSpecies,
): SpeciesProfile {
  const rich = SPECIES_PROFILES[id];
  if (rich) return rich;

  const catalogSpecies = species ?? getCatalogSpeciesById(id);
  if (!catalogSpecies) {
    return {
      family: "Unknown",
      size: "",
      habitat: "",
      range: "",
      diet: "",
      summary: "",
      field_marks: [],
      curated: false,
    };
  }

  return fallbackProfile(catalogSpecies);
}
